### ISSUE TITLE
Remove data-extraction (CLI) and scenarios covering optional features from FSD

### ISSUE THREAD

**Issue by Gordin508** [insightmind/MORR#127]
As the CLI is no longer needed/used for event data extraction from the container, the FSD shold be updated appropriately.
Relevant points/sections: **FS330, TC300, 9.2.1, 10.3.1**

Also remove scenarios  **9.1.3, 9.1.4** as those cover optional features which have not been implemented.

**Comment by Gordin508** [comment]
TC300 already removed in #157

**Comment by limingyialpha** [comment]
All mentioned above are either removed or updated,
All occurrence of data extraction with CLI and optional features are searched found and investigated.
Additionally found section 9.3 also uses optional features, already updated.
