### ISSUE TITLE
Update SD document

### ISSUE THREAD

**Issue by sjend** [insightmind/MORR#169]
The tests necessitated a number of changes to the architecture (particularly regarding how producers utilize native methods). These changes need to be reflected in the Software Design document.

**Comment by sjend** [comment]
Changes I am aware of:
UI: Added ConfirmationDialog, Added (auto-generated) classes for localization (unsure if we want to document those)
Core: Added CryptoHelper

**Comment by limingyialpha** [comment]
<H2>Changes I am aware of:</H2>
<H3>1. Keyboard </H3>

- KeyboardInteractEvent: Some new properties added, old properties renamed

<H3>2. In all Events </H3>

- The definition of the property should include the full declaration.
For example `public  System.Windows.WindowState WindowState` 
instead of `public WindowState WindowState`

**Comment by insightmind** [comment]
Changes I am aware of:

Shared: 
- GlobalHook and added INativeHookMethods, NativeHookMethods

Core:
- Added overrides of Equals and GetHash (dunno if necessary to mention in SD document)
- DesktopCaptureConfiguration changed properties PromptUserForMonitorSelection, MonitorIndex  from private set to set
- GlobalModuleConfiguration changed properties EnabledModules from private set to set
- SessionConfiguration changed properties Encoders, Decoders, RecordingDirectory from private set to set
- Added constructors and property for injecting filesystem in ConfigurationManager
- Added constructors and property for injecting filesystem in JsonDecoder
- Added constructors and property for injecting filesystem in JsonEncoder
- Added constructors and property for injecting filesystem in MpegEncoder
- Added constructors and property for injecting filesystem in SessionManager
