### ISSUE TITLE
ClipboardModule errors when restarted

### ISSUE THREAD

**Issue by Gordin508** [insightmind/MORR#172]
Tested on Microsoft WordPad:

**Prerequisite**: MORR has been launched, a recording started, stopped and started again.
**Actual Behavior**: The ClipboardModule does not record ClipboardCopyEvents during the second (and subsequent) recordings. ClipboardPasteEvents are still created.

**Additional finding**: While the ClipboardModule is active, attempting to paste will sometimes not actually paste the text, but play a Windows error sound instead (subsequent attempts to paste without recopying the text might succeed however). This also occurs on the first recording and not only on subsequent recordings.

**Comment by sjend** [comment]
Fixed in commit 687621b6f6f53585b221ad9df4de637270be8ed9 / Closed with #153
