### ISSUE TITLE
TestJsonIntermediateFormatSerializer_SetActive probable race condition

### ISSUE THREAD

**Issue by Gordin508** [insightmind/MORR#190]
In rare cases (on my machine about 10% chance), the test `TestJsonIntermediateFormatSerializer_SetActive` of `JsonIntermediateFormatSerializerTest` (MORRTest) will fail with `Assert.IsTrue failed. Did not receive serialized event in time!`, most likely due to a race condition.

**Comment by insightmind** [comment]
Can you check if this issue is fixed by a4d483b2c543f5d76f533f20a09e29331b0fa4bf as I am not able to reproduce this on my machine.
