### ISSUE TITLE
Implement WindowResizingProducer

### ISSUE THREAD

**Issue by insightmind** [insightmind/MORR#24]
# Explanation

The goal of this issue is to implement the producer for the WindowResizingEvent.

# Relevant links or documents

You can find the specification of these elements in the SoftwareDesign document.

**Comment by Gordin508** [comment]
Relevant message currently supported by GlobalHook: **WM_SIZE** https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-size
The updated window-width and -height will be stored in Data[0] and Data[1] of the HookMessage struct respectively.
