### ISSUE TITLE
Implement and refine UI

### ISSUE THREAD

**Issue by insightmind** [insightmind/MORR#38]
# Explanation

The goal of this issue is to implement the UI namespace and refine the existing implementation to fit our needs.

After this issue the application should be able to be run using the UI namespace and show the user interface defined in the functional specification document.

You may also include UITests for the application.

# Relevant links or documents

You can find the specification of these elements in the SoftwareDesign document

**Comment by sjend** [comment]
Starting with #96, the Core provides both the most recent/current recording directory through `ISessionManager.CurrentRecordingDirectory` and the path to the folder containing the recording subdirectories through `ISessionManager.RecordingsFolder`. Implementers may use those to facilitate the deletion of a recording or the opening of the recordings folder on button press.
