### ISSUE TITLE
Implement multi-monitor recording and encoding

### ISSUE THREAD

**Issue by sjend** [insightmind/MORR#52]
### Explanation

The current implementation of desktop video capture only supports a single screen for recording. As researchers might be utilizing multiple screens during a research session, the ability to capture the content of multiple screens may be desireable. If possible, the captured video streams should then be encoded on separate video tracks and stored in the same container.

**Comment by Gordin508** [comment]
Note: If the MonitorPicker pops up (iirc it doesn't happen on the newest edition of windows), you can select both monitors, but the resolution will still stay at the default (1920x1080) and the resulting video gets letterboxed to preserve the aspect ratio (monitor outputs are shown side-by-side).

**Comment by sjend** [comment]
Closing this as the desired functionality may be achieved just using the picker as mentioned above - The picker itself can be forced by setting `PromptUserForMonitorSelection` in the configuration regardless of Windows version, so an explicit implementation is not necessary.
