### ISSUE TITLE
Map virtual key codes to char

### ISSUE THREAD

**Issue by sjend** [insightmind/MORR#74]
### Explanation

In the current implementation, the `KeyboardInteractEvent` specifies the pressed key only using its virtual keycode. As per request, the desired functionality instead specifies the pressed key by the `char` that it maps to, though we may wish to keep the virtual keycode.
Implementers may use `MapVirtualKeyA` to implement this functionality. Implementers should also investigate the need to determine the current keyboard locale of the process that the keypress event originated from and performing the mapping in accordance with this - potentially differing - keyboard locale, though it is to be expected that this may be neither feasible nor necessary.

**Comment by Gordin508** [comment]
I haven't tested this, but hooking the WM_CHAR message instead of WM_KEYDOWN might already provide the desired information: https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-char

>Posted to the window with the keyboard focus when a WM_KEYDOWN message is translated by the TranslateMessage function. The WM_CHAR message contains the character code of the key that was pressed.

**Comment by sjend** [comment]
As far as I can tell (without having tested this), `WM_KEYDOWN` (which is the message that would have to be translated with `TranslateMessage` before `WM_CHAR` would get sent) is only raised when ALT is not pressed.
(see https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-keydown)
> Posted to the window with the keyboard focus when a nonsystem key is pressed. A nonsystem key is a key that is pressed when the ALT key is not pressed.

As such I don't think it would be possible to completely replace the low-level keyboard hook with `WM_CHAR` without potentially losing data. I am also not sure if it would be desireable to replace the low-level keyboard hook with a global hook at all; despite our best efforts, global hooks will probably be less stable and less performant than low-level hooks. Implementers might nonetheless make use of `WM_CHAR` if this proves to be beneficial.

**Comment by insightmind** [comment]
Whats the actual plan in which format we want to convert the characters? I probably suggest Unicode. You can use https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-mapvirtualkeyexa for this as it already translates the virtualkey to the correct keyboard locale. However in my tests it does not respect the current modifier keys, e.g. if you press both `shift and 2` on the US keyboard layout the actual char should be `@` however the MapVirtualKeyEx gives you `2`. To fix this you may use https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-mapvirtualkeyexa however it is a bit more complex to implement.
